# Generated by Django 3.1.1 on 2021-06-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
    ]
